# Generated by Django 5.1.7 on 2025-12-24 08:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MRIPatientData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('mobile', models.CharField(max_length=15)),
                ('predicted_disease', models.CharField(blank=True, max_length=200, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctor.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='PatientSkinData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('contact', models.CharField(max_length=15)),
                ('sym1', models.CharField(choices=[('0', 'Itching'), ('1', 'Redness'), ('2', 'Rash'), ('3', 'Scaling'), ('4', 'Blister'), ('5', 'Pus Filled'), ('6', 'Pain'), ('7', 'Dry Skin'), ('8', 'Swelling'), ('9', 'Burning'), ('10', 'Cracks'), ('11', 'Circular Rash'), ('12', 'Oozing'), ('13', 'Fever'), ('14', 'Hair Loss'), ('15', 'Dark Spot'), ('16', 'Numbness'), ('17', 'Ulcer'), ('18', 'Peeling'), ('19', 'Thickness')], max_length=20)),
                ('sym2', models.CharField(choices=[('0', 'Itching'), ('1', 'Redness'), ('2', 'Rash'), ('3', 'Scaling'), ('4', 'Blister'), ('5', 'Pus Filled'), ('6', 'Pain'), ('7', 'Dry Skin'), ('8', 'Swelling'), ('9', 'Burning'), ('10', 'Cracks'), ('11', 'Circular Rash'), ('12', 'Oozing'), ('13', 'Fever'), ('14', 'Hair Loss'), ('15', 'Dark Spot'), ('16', 'Numbness'), ('17', 'Ulcer'), ('18', 'Peeling'), ('19', 'Thickness')], max_length=20)),
                ('sym3', models.CharField(choices=[('0', 'Itching'), ('1', 'Redness'), ('2', 'Rash'), ('3', 'Scaling'), ('4', 'Blister'), ('5', 'Pus Filled'), ('6', 'Pain'), ('7', 'Dry Skin'), ('8', 'Swelling'), ('9', 'Burning'), ('10', 'Cracks'), ('11', 'Circular Rash'), ('12', 'Oozing'), ('13', 'Fever'), ('14', 'Hair Loss'), ('15', 'Dark Spot'), ('16', 'Numbness'), ('17', 'Ulcer'), ('18', 'Peeling'), ('19', 'Thickness')], max_length=20)),
                ('sym4', models.CharField(blank=True, choices=[('0', 'Itching'), ('1', 'Redness'), ('2', 'Rash'), ('3', 'Scaling'), ('4', 'Blister'), ('5', 'Pus Filled'), ('6', 'Pain'), ('7', 'Dry Skin'), ('8', 'Swelling'), ('9', 'Burning'), ('10', 'Cracks'), ('11', 'Circular Rash'), ('12', 'Oozing'), ('13', 'Fever'), ('14', 'Hair Loss'), ('15', 'Dark Spot'), ('16', 'Numbness'), ('17', 'Ulcer'), ('18', 'Peeling'), ('19', 'Thickness')], max_length=20, null=True)),
                ('sym5', models.CharField(blank=True, choices=[('0', 'Itching'), ('1', 'Redness'), ('2', 'Rash'), ('3', 'Scaling'), ('4', 'Blister'), ('5', 'Pus Filled'), ('6', 'Pain'), ('7', 'Dry Skin'), ('8', 'Swelling'), ('9', 'Burning'), ('10', 'Cracks'), ('11', 'Circular Rash'), ('12', 'Oozing'), ('13', 'Fever'), ('14', 'Hair Loss'), ('15', 'Dark Spot'), ('16', 'Numbness'), ('17', 'Ulcer'), ('18', 'Peeling'), ('19', 'Thickness')], max_length=20, null=True)),
                ('sym6', models.CharField(blank=True, choices=[('0', 'Itching'), ('1', 'Redness'), ('2', 'Rash'), ('3', 'Scaling'), ('4', 'Blister'), ('5', 'Pus Filled'), ('6', 'Pain'), ('7', 'Dry Skin'), ('8', 'Swelling'), ('9', 'Burning'), ('10', 'Cracks'), ('11', 'Circular Rash'), ('12', 'Oozing'), ('13', 'Fever'), ('14', 'Hair Loss'), ('15', 'Dark Spot'), ('16', 'Numbness'), ('17', 'Ulcer'), ('18', 'Peeling'), ('19', 'Thickness')], max_length=20, null=True)),
                ('sym7', models.CharField(blank=True, choices=[('0', 'Itching'), ('1', 'Redness'), ('2', 'Rash'), ('3', 'Scaling'), ('4', 'Blister'), ('5', 'Pus Filled'), ('6', 'Pain'), ('7', 'Dry Skin'), ('8', 'Swelling'), ('9', 'Burning'), ('10', 'Cracks'), ('11', 'Circular Rash'), ('12', 'Oozing'), ('13', 'Fever'), ('14', 'Hair Loss'), ('15', 'Dark Spot'), ('16', 'Numbness'), ('17', 'Ulcer'), ('18', 'Peeling'), ('19', 'Thickness')], max_length=20, null=True)),
                ('sym8', models.CharField(blank=True, choices=[('0', 'Itching'), ('1', 'Redness'), ('2', 'Rash'), ('3', 'Scaling'), ('4', 'Blister'), ('5', 'Pus Filled'), ('6', 'Pain'), ('7', 'Dry Skin'), ('8', 'Swelling'), ('9', 'Burning'), ('10', 'Cracks'), ('11', 'Circular Rash'), ('12', 'Oozing'), ('13', 'Fever'), ('14', 'Hair Loss'), ('15', 'Dark Spot'), ('16', 'Numbness'), ('17', 'Ulcer'), ('18', 'Peeling'), ('19', 'Thickness')], max_length=20, null=True)),
                ('sym9', models.CharField(blank=True, choices=[('0', 'Itching'), ('1', 'Redness'), ('2', 'Rash'), ('3', 'Scaling'), ('4', 'Blister'), ('5', 'Pus Filled'), ('6', 'Pain'), ('7', 'Dry Skin'), ('8', 'Swelling'), ('9', 'Burning'), ('10', 'Cracks'), ('11', 'Circular Rash'), ('12', 'Oozing'), ('13', 'Fever'), ('14', 'Hair Loss'), ('15', 'Dark Spot'), ('16', 'Numbness'), ('17', 'Ulcer'), ('18', 'Peeling'), ('19', 'Thickness')], max_length=20, null=True)),
                ('sym10', models.CharField(blank=True, choices=[('0', 'Itching'), ('1', 'Redness'), ('2', 'Rash'), ('3', 'Scaling'), ('4', 'Blister'), ('5', 'Pus Filled'), ('6', 'Pain'), ('7', 'Dry Skin'), ('8', 'Swelling'), ('9', 'Burning'), ('10', 'Cracks'), ('11', 'Circular Rash'), ('12', 'Oozing'), ('13', 'Fever'), ('14', 'Hair Loss'), ('15', 'Dark Spot'), ('16', 'Numbness'), ('17', 'Ulcer'), ('18', 'Peeling'), ('19', 'Thickness')], max_length=20, null=True)),
                ('predicted_disease', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctor.doctor')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
