# Generated by Django 5.2.10 on 2026-02-02 09:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='mripatientdata',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mripatientdata',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='mri_scans/'),
        ),
    ]
